language: node_js
node_js:
    - "8"
    - "10"
before_install:
    - sudo apt-get update
    - sudo apt-get install libpcap-dev
    - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
    - npm run lint
after_script: greenkeeper-lockfile-upload
